### ISSUE TITLE
Missing File Conflicts Check Feedback

### ISSUE THREAD

**Issue by shundhammer** [shundhammer/yqpkg#13]
After all involved packages have been downloaded, libyzpp checks for file conflicts again based on the actual file lists in the downloaded packages. That can take a while; there should be some user feedback.

Proposal: Show a pop-up with a progress bar.

**Comment by shundhammer** [comment]
We now have a progress dialog if the file conflicts check takes longer than 1.5 seconds.

It's a custom dialog with better visual appearance than the standard Qt one:

![yqpkg-file-conflicts-progress-dialog](https://github.com/user-attachments/assets/c3773bc1-a0d8-4235-9109-022d60eb1e41)

It's a non-modal dialog, i.e. you can interact with widgets in the main window while it's open. Its "Close" button only closes the dialog; it does not abort the commit or cancel checking for file conflicts.

**Comment by shundhammer** [comment]
If there are any file conflicts, the first 10 of them are reported, each one in a separate warning pop-up:

![file-conflict-01](https://github.com/user-attachments/assets/13e9f35e-fc3b-4da8-ab8e-609e41d19f73)

This uses the standard libzypp formatting for file conflicts.

It would be pointless to report more than 10 file conflicts; if there are any, you are screwed anyway. And you have to click each one away separately, so even displaying 10 is annoying enough; but not anywhere near as annoying than a wrecked system which might be the result of continuing anyway despite the file conflicts.

The transaction will be aborted if there are any file conflicts. This will leave the system in a well-defined state since in the normal setup, all packages that are to be installed or updated are downloaded first, then there is the file conflicts check, and only then any packages are actually installed or updated (or removed? Ask the libzypp experts).

**Comment by shundhammer** [comment]
This is closed with   3208d6a56c52b78ad4f8f8938f9632f1068ae0ea and 95b0a8660df54828e65d6b38abdc19716785892c .

**Comment by shundhammer** [comment]
I just realized that you can go back to the package selector to deselect a package that caused file conflicts: The file conflicts are detected and displayed, then you get to the summary page, from where you can simply go back to change the package selection; no work lost.

**Comment by gruenich** [comment]
Two comments:
1. "File conflict" is a generic term. Could a more precise term be used like "Checking package's content for file conflicts" or whatever exactly is happening. Someone vaguely into the process should be able to figure out what happens / happened.
2. Does the dialog steal focus if YQPkg is in the background. YaST Software is super annoying as it has a pop-up for post-install scripts doing so.

**Comment by shundhammer** [comment]
"File conflict" is a well-established term in the context of package management. I learned over the decades that it does not pay off to assume the least-informed users as the standard; that only leads to awkward and very verbose messages that advanced users can't understand anymore. Novice users will have to learn a few things.

About the focus thing: This was a leftover from the times when YaST had to run without a window manager in the inst-sys, so it had to do all kinds of window management things by itself; things like the window stacking order or grabbing the keyboard focus for a new window. None of that applies to YQPkg.
