### ISSUE TITLE
Flatpak support and "AppimageLauncher-like" functionality?

### ISSUE THREAD

**Issue by SpaLox1** [shundhammer/yqpkg#24]
In the long term, it would be great if yqpkg assisted the user in the general management of desktop software, like,

-Installing, updating and deleting Flatpaks
-Updating AppImages (like AppImageLauncher)

Maybe someone can add something like a plugin system for yqpkg to extend its functionality?

**Comment by shundhammer** [comment]
First it needs all the basic functionality before we can even think of extending the scope.

I am by no means an expert about FlatPak, AppImage or Snaps. But I do know that they each have their very own philosophy, and like every software packaging system on this planet, they reinvent the wheel the umpteenth time. 

RPM, Debian DEB, Perl CPAN, Python PIP, Rust Crates, Ruby Gems, Java Whatchamacallits, you name it; and now it's those bundle-the-world huge package formats like FlatPak, AppImage, Snap. Every single one of them is incompatible with everything else, every single one of them has some way of dealing with dependencies, every single one of them has its own command line tool that is of course completely incompatible in every way to any of the others.

If there is a common denominator among them, it is that they are incompatible. That's not much to write some software that can operate with any reasonable number of them.

I wrote a [packages view](https://github.com/shundhammer/qdirstat/blob/master/doc/Pkg-View.md) for my QDirStat some years ago to visualize packages, and it works with RPM, Debian DEB and Arch / Manjaro PackMan packages, but that's only for listing packages and their file lists; just simple read-only access. And they are all Linux-native package formats that share the same philosophies.

The large bundle package formats don't quite fit into that scheme. And of course there is no libzypp support for any of them (as far as I know), and that's the killer argument.

So for the forseeable future I don't think that support for FlatPak & Co. is realistic.
